name: Prepare NodeJS
description: Setup and Cache NodeJS

inputs:
  node-version:
    description: NodeJS version
    required: true
    default: 16.15.1

runs:
  using: "composite"
  steps:
    - name: 🐢 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ input.node-version }}

    - name: 💵 Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: ⬇️ Install Dependencies
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install